### ISSUE TITLE
Tabs being placed instead of spaces - Joplin 2.8.8

### ISSUE THREAD

**Issue by terminal-root** [alondmnt/joplin-plugin-space-indenter#1]
When I press tab on an empty line or at mid-line, a tab is inserted instead of spaces. The plugin is toggled on in Joplin settings.
Did I miss possibly some necessary configuration somewhere?
```
sysinfo w/ unnecessary details redacted
██████████████████  ████████   
██████████████████  ████████   ----------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████  
████████            ████████   Kernel: 5.15.49-1-MANJARO 
████████  ████████  ████████   
████████  ████████  ████████   
████████  ████████  ████████   
████████  ████████  ████████   
████████  ████████  ████████   DE: Xfce 4.16 
████████  ████████  ████████   WM: Xfwm4 
████████  ████████  ████████   [redacted]
████████  ████████  ████████   
████████  ████████  ████████   
```

**Comment by alondmnt** [comment]
Hi @terminal-root,
I know this may not be what one expects, but this is CodeMirror's behavior.
You can press `Cmd+]` to get the expected behavior on an empty line or at mid-line.
I hope the [following table](https://github.com/alondmnt/joplin-plugin-space-indenter/#readme) in the README describes it well enough.
